index:
    path: /
    controller: App\Controller\DefaultController::index
    
test:
    path: /test
    controller: App\Controller\DefaultController::test

Profile:
    path: /profile
    controller: App\Controller\DefaultController::profile
